project:
  type: website
  output-dir: docs

website:
  title: "Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobbies.qmd
        text: Hobbies
      - href: travel_exp.qmd
        text: Travel Experiences

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true